### ISSUE TITLE
How to build 

### ISSUE THREAD

**Issue by anikitin** [oasdiff/oasdiff-service#35]
I'd like to run the server locally.
There are no build instructions in README. All my attempts to build end with the following:

```
internal\breaking_changes.go:94:21: undefined: checker.LoadOpenAPISpecInfo
internal\breaking_changes.go:99:21: undefined: checker.LoadOpenAPISpecInfo  
```

Sorry, not a specialist in golang. Can you please point me what I am doing wrong?

Thanks.

**Comment by effoeffi** [comment]
thanks @anikitin, [this commit](https://github.com/oasdiff/oasdiff-service/commit/e8453d94bfb2930cf8eeed1f47d7bdd5ec0161c7) should fix that :)
