### ISSUE TITLE
breaking-changes 

### ISSUE THREAD

**Issue by Angel0926** [oasdiff/oasdiff-service#53]
hi i want use this curl :   

curl -X POST \
    -F base= https://swaggerhub.................../swagger.yaml\
    -F revision=@target/generated/openapi.yaml \
    https://api.oasdiff.com/tenants/{tenant-id}/breaking-changes 

for swagger breaking-changes(contract testing) 
i compared my local generated openapi.yaml and swagger yaml from swaggerhub.  When i changed for example my endpoint(deleted) i wait that build was failed but  my build passed.  

how to do it right?
<img width="668" alt="Screenshot 2023-09-06 at 12 31 46" src="https://github.com/oasdiff/oasdiff-service/assets/91777306/ac8f1a6c-d25a-4b05-859c-56e97eeb77ed">

**Comment by effoeffi** [comment]
Hello @Angel0926,

You need to create a tenant first (see ["creating a tenant" in readme](https://github.com/oasdiff/oasdiff-service#creating-a-tenant)).
Than replace the `{tenant-id}` with the ID you got when creating the tenant.

Can you please explain more about your use case? 
Are you using it as part of your code? Or in your CI pipeline?
Have you tried to run it locally with the [oasdiff CLI or Docker](https://github.com/Tufin/oasdiff)?

I'm happy to help you get started. Just let me know if you have any questions.

Thanks,
Effi

**Comment by Angel0926** [comment]
i use it in my build plan, for contract testing

**Comment by effoeffi** [comment]
> curl: (6) Could not resolve host: auth.oasdiff.com

Right @Angel0926, we are working on fixing that and will let you know as soon as it is fixed

**Comment by Angel0926** [comment]
thanks, can you tell me how long it will take?

**Comment by effoeffi** [comment]
@Angel0926 it's working with a new host name `https://register.oasdiff.com/tenants`.
I also updated the readme, please, let me know if it is working for you.

**Comment by Angel0926** [comment]
I tried it passes but there is no answer (empty answer) does not return id

<img width="895" alt="Screenshot 2023-09-07 at 10 43 09" src="https://github.com/oasdiff/oasdiff-service/assets/91777306/8918be2c-8958-487f-ba9f-f1fc045876b8">

**Comment by effoeffi** [comment]
> I tried it passes but there is no answer (empty answer) does not return id

@Angel0926 it is probably empty because the request failed with a `400 Bad Request`. Are you using a valid email address?
You can add `-i` flag to `curl` in order to see the response headers.
Do you want to take it offline?

**Comment by Angel0926** [comment]
yes it's a real email address, no i take it online

**Comment by Angel0926** [comment]
this is right?  https://api.oasdiff.com/tenants/{88708k9d-8c06-4a39-9f5c-148r52567kjk}/breaking-changes

**Comment by effoeffi** [comment]
Please, DO NOT publish your tenant ID

> this is right? [https://api.oasdiff.com/tenants/{abc}/breaking-changes](https://api.oasdiff.com/tenants/%7Babc%7D/breaking-changes) becouse When i changed for example my endpoint(deleted) i wait that build was failed but my build passed.

For tenant ID `abc` the URL should look like this: `https://api.oasdiff.com/tenants/abc/breaking-changes` without the curly brackets

**Comment by Angel0926** [comment]
Thanks, I'll try it now. it was a fictitious id and not a real one :)

**Comment by Angel0926** [comment]
what breaks the contract? what to try to understand if it works or not. I tried delete endpoint, but its not work

**Comment by effoeffi** [comment]
> what breaks the contract? what to try to understand if it works or not. I tried delete endpoint, but its not work

@Angel0926 can you share specs? what is the HTTP response code that you are getting?

**Comment by Angel0926** [comment]
@effoeffi  
<img width="716" alt="Screenshot 2023-09-07 at 22 06 12" src="https://github.com/oasdiff/oasdiff-service/assets/91777306/04b4bbad-c174-4e11-bcf4-81427db6d46c">
this is the answer if there are changes and if not

**Comment by effoeffi** [comment]
Unfortunately this is not telling me much.
I asked for sharing your specs and what is the HTTP response code?
Is it 201?

You can run the example in the readme (after copy the specs under data) with your `tenant-id`:
```
curl -i -X POST \
    -F base=@data/openapi-test1.yaml \
    -F revision=@data/openapi-test3.yaml \
    https://api.oasdiff.com/tenants/{tenant-id}/breaking-changes
```
Note that I added `-i` flag so you will be able to see also the HTTP response code (it should be 201).

**Comment by Angel0926** [comment]
@effoeffi  Thank you for help 
<img width="659" alt="Screenshot 2023-09-08 at 11 23 15" src="https://github.com/oasdiff/oasdiff-service/assets/91777306/7c577f17-45b9-49f0-ab8f-d6b27849ff6b">

**Comment by Angel0926** [comment]
it be 201). but i deleted one  endpoint from api, it shouldn't have fallen?

**Comment by effoeffi** [comment]
> it be 201). but i deleted one endpoint from api, it shouldn't have fallen?

Not fall, but you should get a breaking change (I guess that is what you mean).
the deleted endpoint should be part of the revision.
Additionally, as I suggested, if you share the specs, I can help more.

**Comment by Angel0926** [comment]
yes i want get a breaking change) what you mean by specs?

**Comment by effoeffi** [comment]
I mean Open API specs, you are sending a base and a revision as part of the HTTP request, can you share it?

**Comment by Angel0926** [comment]
sorry no) but I want to understand what I can change so that the build fails

**Comment by effoeffi** [comment]
>sorry no) but I want to understand what I can change so that the build fails

If you are looking for a list of Examples of Breaking and Non-Breaking Changes see [here](https://github.com/Tufin/oasdiff/blob/main/BREAKING-CHANGES-EXAMPLES.md)

>I swapped the contents of base and revision and now I can see the list of changes, but the build is passing) but I need to fail the build , if i have a breaking change Shouldn't the build fail?

If you are running this code in the CI and you want the build to fail in case there are breaking changes, you can check if there are items in the response and in this case break the build.

**Comment by Angel0926** [comment]
Thank you but --fail-on ERR dont work with curl, what i can use ?

**Comment by effoeffi** [comment]
>@effoeffi Thank you but --fail-on ERR dont work with curl, what i can use ?

Can you, please, share the command you are running, and the response you expect, so I can try to reproduce the issue?

**Comment by Angel0926** [comment]
@Angel0926 

curl -i -X POST \
    -F base=@/openapi.yaml \
    -F revision=https://swaggerhub......./swagger.yaml \
    https://api.oasdiff.com/tenants/...../breaking-changes \
    --fail-on ERR.        
<img width="583" alt="Screenshot 2023-09-11 at 15 05 16" src="https://github.com/oasdiff/oasdiff-service/assets/91777306/4286427e-8515-4175-9e57-894340783ef5">

**Comment by Angel0926** [comment]
HOW CAN I GIVE SWAGGER LATEST VERSION or revision?

**Comment by effoeffi** [comment]
>curl -i -X POST
-F base=@/openapi.yaml
-F revision=https://swaggerhub......./swagger.yaml
https://api.oasdiff.com/tenants/...../breaking-changes
--fail-on ERR.

You are running `curl` which is not my tool, but a tool for running HTTP requests

For breaking the build you can:
1. Use [oasdiff cli](https://github.com/Tufin/oasdiff/blob/main/README.md)
2. Like explained above:
>If you are running this code in the CI and you want the build to fail in case there are breaking changes, you can check if there are items in the response and in this case break the build.

**Comment by Angel0926** [comment]
but my code work with curl (

**Comment by Angel0926** [comment]
@effoeffi how i can give latest swagger version?

**Comment by effoeffi** [comment]
>@effoeffi how i can give latest swagger version?

I suggest reading swagger docs

**Comment by Angel0926** [comment]
thanks a lot
